#!/usr/bin/env python
import sys
import traceback
import paramiko
from paramiko_expect import SSHClientInteraction

reload(sys)
sys.setdefaultencoding('gbk')

PROMPT = '.+>$|.+]$|.+#\s*$|.+\$|.+---- More ----$'

def exeSSHCmds(ip, username, password, cmds):
    try:
        client = paramiko.SSHClient()
        client.load_system_host_keys()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(hostname=ip, username=username, password=password, timeout=10, allow_agent=False, look_for_keys=False)
        cmd_output = ""
        with SSHClientInteraction(client, timeout=15, display=True) as interact:
            interact.encoding = "gbk"
            interact.expect(PROMPT, timeout=15)
            for cmd in cmds:
                interact.send(cmd)
                interact.expect(PROMPT, timeout=15)
                cmd_output = cmd_output + cmd +"\r\n"+ interact.current_output_clean
        return cmd_output
    except Exception:
        traceback.print_exc()
    finally:
        try:
            client.close()
        except:
            pass
if __name__ == '__main__':
    pass
